config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resource :lint, only: [:show, :create]

  resource :help do
    get :oauth2
  end

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status, to: 'projects#badge'
      get :integration
      post :build
      post :toggle_shared_runners
      get :dumped_yaml
    end

    resources :services, only: [:index, :edit, :update] do
      member do
        get :test
      end
    end

    resource :charts, only: [:show]

    resources :refs, constraints: { ref_id: /.*/ }, only: [] do
      resources :commits, only: [:show] do
        member do
          get :status
          get :cancel
        end
      end
    end

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :web_hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end

    resources :triggers, only: [:index, :create, :destroy]

    resources :runners, only: [:index, :edit, :update, :destroy, :show] do
      member do
        get :resume
        get :pause
      end
    end

    resources :runner_projects, only: [:create, :destroy]

    resources :events, only: [:index]
    resource :variables, only: [:show, :update]
  end

  resource :user_sessions do
    get :auth
    get :callback
  end

  namespace :admin do
    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        put :assign_all
        get :resume
        get :pause
      end
    end

    resources :events, only: [:index]

    resources :projects do
      resources :runner_projects
    end

    resources :builds, only: :index

    resource :application_settings, only: [:show, :update]
  end

  root to: 'projects#index'
end

app/models/service.rb
# == Schema Information
#
# Table name: services
#
#  id         :integer          not null, primary key
#  type       :string(255)
#  title      :string(255)
#  project_id :integer          not null
#  created_at :datetime
#  updated_at :datetime
#  active     :boolean          default(FALSE), not null
#  properties :text
#

# To add new service you should build a class inherited from Service
# and implement a set of methods
class Service < ActiveRecord::Base
  serialize :properties, JSON

  default_value_for :active, false

  after_initialize :initialize_properties

  belongs_to :project

  validates :project_id, presence: true

  def activated?
    active
  end

  def category
    :common
  end

  def initialize_properties
    self.properties = {} if properties.nil?
  end

  def title
    # implement inside child
  end

  def description
    # implement inside child
  end

  def help
    # implement inside child
  end

  def to_param
    # implement inside child
  end

  def fields
    # implement inside child
    []
  end

  def can_test?
    project.builds.any?
  end

  def can_execute?(build)
    true
  end

  def execute(build)
    # implement inside child
  end

  # Provide convenient accessor methods
  # for each serialized property.
  def self.prop_accessor(*args)
    args.each do |arg|
      class_eval %{
        def #{arg}
          (properties || {})['#{arg}']
        end

        def #{arg}=(value)
          self.properties ||= {}
          self.properties['#{arg}'] = value
        end
      }
    end
  end

  def self.boolean_accessor(*args)
    self.prop_accessor(*args)

    args.each do |arg|
      class_eval %{
        def #{arg}?
          ActiveRecord::ConnectionAdapters::Column::TRUE_VALUES.include?(#{arg})
        end
      }
    end
  end
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_filter :authenticate_user!
  before_filter :project
  before_filter :authorize_access_project!
  before_filter :authorize_manage_project!
  before_filter :service, only: [:edit, :update, :test]

  respond_to :html

  layout 'project'

  def index
    @project.build_missing_services
    @services = @project.services.reload
  end

  def edit
  end

  def update
    if @service.update_attributes(service_params)
      redirect_to edit_project_service_path(@project, @service.to_param), notice: 'Service was successfully updated.'
    else
      render 'edit'
    end
  end

  def test
    last_build = @project.builds.last

    if @service.execute(last_build)
      message = { notice: 'We successfully tested the service' }
    else
      message = { alert: 'We tried to test the service but error occurred' }
    end

    redirect_to :back, message
  end

  private

  def project
    @project = Project.find(params[:project_id])
  end

  def service
    @service ||= @project.services.find { |service| service.to_param == params[:id] }
  end

  def service_params
    params.require(:service).permit(
      :type, :active, :webhook, :notify_only_broken_builds,
      :email_recipients, :email_only_broken_builds, :email_add_pusher,
      :hipchat_token, :hipchat_room, :hipchat_server
    )
  end
end

app/views/services/_form.html.haml
%h3.page-title
  = @service.title
  = boolean_to_icon @service.activated?

%p= @service.description

.back-link
  = link_to project_services_path(@project) do
    &larr; to services

%hr

= form_for(@service, as: :service, url: project_service_path(@project, @service.to_param), method: :put, html: { class: 'form-horizontal' }) do |f|
  - if @service.errors.any?
    .alert.alert-danger
      %ul
        - @service.errors.full_messages.each do |msg|
          %li= msg

  - if @service.help.present?
    .bs-callout
      = @service.help

  .form-group
    = f.label :active, "Active", class: "control-label"
    .col-sm-10
      = f.check_box :active

  - @service.fields.each do |field|
    - name = field[:name]
    - label = field[:label] || name
    - value = @service.send(name)
    - type = field[:type]
    - placeholder = field[:placeholder]
    - choices = field[:choices]
    - default_choice = field[:default_choice]
    - help = field[:help]

    .form-group
      = f.label label, class: "control-label"
      .col-sm-10
        - if type == 'text'
          = f.text_field name, class: "form-control", placeholder: placeholder
        - elsif type == 'textarea'
          = f.text_area name, rows: 5, class: "form-control", placeholder: placeholder
        - elsif type == 'checkbox'
          = f.check_box name
        - elsif type == 'select'
          = f.select name, options_for_select(choices, value ? value : default_choice), {}, { class: "form-control" }
        - if help
          .light #{help}

  .form-actions
    = f.submit 'Save', class: 'btn btn-save'
    &nbsp;
    - if @service.valid? && @service.activated? && @service.can_test?
      = link_to 'Test settings', test_project_service_path(@project, @service.to_param), class: 'btn'

app/views/services/edit.html.haml
= render 'form'

app/views/services/index.html.haml
%h3.page-title Project services
%p.light Project services allow you to integrate GitLab CI with other applications

%table.table
  %thead
    %tr
      %th
      %th Service
      %th Desription
      %th Last edit
  - @services.sort_by(&:title).each do |service|
    %tr
      %td
        = boolean_to_icon service.activated?
      %td
        = link_to edit_project_service_path(@project, service.to_param) do
          %strong= service.title
      %td
        = service.description
      %td.light
        = time_ago_in_words service.updated_at
        ago