config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resource :lint, only: [:show, :create]

  resource :help do
    get :oauth2
  end

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status, to: 'projects#badge'
      get :integration
      post :build
      post :toggle_shared_runners
      get :dumped_yaml
    end

    resources :services, only: [:index, :edit, :update] do
      member do
        get :test
      end
    end

    resource :charts, only: [:show]

    resources :refs, constraints: { ref_id: /.*/ }, only: [] do
      resources :commits, only: [:show] do
        member do
          get :status
          get :cancel
        end
      end
    end

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :web_hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end

    resources :triggers, only: [:index, :create, :destroy]

    resources :runners, only: [:index, :edit, :update, :destroy, :show] do
      member do
        get :resume
        get :pause
      end
    end

    resources :runner_projects, only: [:create, :destroy]

    resources :events, only: [:index]
    resource :variables, only: [:show, :update]
  end

  resource :user_sessions do
    get :auth
    get :callback
  end

  namespace :admin do
    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        put :assign_all
        get :resume
        get :pause
      end
    end

    resources :events, only: [:index]

    resources :projects do
      resources :runner_projects
    end

    resources :builds, only: :index

    resource :application_settings, only: [:show, :update]
  end

  root to: 'projects#index'
end

app/models/runner.rb
# == Schema Information
#
# Table name: runners
#
#  id           :integer          not null, primary key
#  token        :string(255)
#  created_at   :datetime
#  updated_at   :datetime
#  description  :string(255)
#  contacted_at :datetime
#  active       :boolean          default(TRUE), not null
#  is_shared    :boolean          default(FALSE)
#  name         :string(255)
#  version      :string(255)
#  revision     :string(255)
#  platform     :string(255)
#  architecture :string(255)
#

class Runner < ActiveRecord::Base
  has_many :builds
  has_many :runner_projects, dependent: :destroy
  has_many :projects, through: :runner_projects

  has_one :last_build, ->() { order('id DESC') }, class_name: 'Build'

  before_validation :set_default_values

  scope :specific, ->() { where(is_shared: false) }
  scope :shared, ->() { where(is_shared: true) }
  scope :active, ->() { where(active: true) }
  scope :paused, ->() { where(active: false) }

  acts_as_taggable

  def self.search(query)
    where('LOWER(runners.token) LIKE :query OR LOWER(runners.description) like :query',
          query: "%#{query.try(:downcase)}%")
  end

  def set_default_values
    self.token = SecureRandom.hex(15) if self.token.blank?
  end

  def assign_to(project, current_user = nil)
    self.is_shared = false if shared?
    self.save
    project.runner_projects.create!(runner_id: self.id)
  end

  def display_name
    return token unless !description.blank?

    description
  end

  def shared?
    is_shared
  end

  def belongs_to_one_project?
    runner_projects.count == 1
  end

  def specific?
    !shared?
  end

  def only_for?(project)
    projects == [project]
  end

  def short_sha
    token[0...10]
  end
end

app/controllers/admin/runners_controller.rb
class Admin::RunnersController < Admin::ApplicationController
  before_filter :runner, except: :index

  def index
    @runners = Runner.order('id DESC')
    @runners = @runners.search(params[:search]) if params[:search].present?
    @runners = @runners.page(params[:page]).per(30)
    @active_runners_cnt = Runner.where("contacted_at > ?", 1.minutes.ago).count
  end

  def show
    @builds = @runner.builds.order('id DESC').first(30)
    @projects = Project.all
    @projects = @projects.search(params[:search]) if params[:search].present?
    @projects = @projects.where("projects.id NOT IN (?)", @runner.projects.pluck(:id)) if @runner.projects.any?
    @projects = @projects.page(params[:page]).per(30)
  end

  def update
    @runner.update_attributes(runner_params)

    respond_to do |format|
      format.js
      format.html { redirect_to admin_runner_path(@runner) }
    end
  end

  def destroy
    @runner.destroy

    redirect_to admin_runners_path
  end

  def resume
    if @runner.update_attributes(active: true)
      redirect_to admin_runners_path, notice: 'Runner was successfully updated.'
    else
      redirect_to admin_runners_path, alert: 'Runner was not updated.'
    end
  end

  def pause
    if @runner.update_attributes(active: false)
      redirect_to admin_runners_path, notice: 'Runner was successfully updated.'
    else
      redirect_to admin_runners_path, alert: 'Runner was not updated.'
    end
  end

  def assign_all
    Project.unassigned(@runner).all.each do |project|
      @runner.assign_to(project, current_user)
    end

    redirect_to admin_runner_path(@runner), notice: "Runner was assigned to all projects"
  end

  private

  def runner
    @runner ||= Runner.find(params[:id])
  end

  def runner_params
    params.require(:runner).permit(:token, :description, :tag_list, :contacted_at, :active)
  end
end

app/controllers/runners_controller.rb
class RunnersController < ApplicationController
  before_filter :authenticate_user!
  before_filter :project
  before_filter :set_runner, only: [:edit, :update, :destroy, :pause, :resume, :show]
  before_filter :authorize_access_project!
  before_filter :authorize_manage_project!

  layout 'project'

  def index
    @runners = @project.runners.order('id DESC')
    @specific_runners = current_user.authorized_runners.
      where.not(id:  @runners).order('runners.id DESC').page(params[:page]).per(20)
    @shared_runners = Runner.shared.active
    @shared_runners_count = @shared_runners.count(:all)
  end

  def edit
  end

  def update
    if @runner.update_attributes(runner_params)
      redirect_to edit_project_runner_path(@project, @runner), notice: 'Runner was successfully updated.'
    else
      redirect_to edit_project_runner_path(@project, @runner), alert: 'Runner was not updated.'
    end
  end

  def destroy
    if @runner.only_for?(@project)
      @runner.destroy
    end

    redirect_to project_runners_path(@project)
  end

  def resume
    if @runner.update_attributes(active: true)
      redirect_to project_runners_path(@project, @runner), notice: 'Runner was successfully updated.'
    else
      redirect_to project_runners_path(@project, @runner), alert: 'Runner was not updated.'
    end
  end

  def pause
    if @runner.update_attributes(active: false)
      redirect_to project_runners_path(@project, @runner), notice: 'Runner was successfully updated.'
    else
      redirect_to project_runners_path(@project, @runner), alert: 'Runner was not updated.'
    end
  end

  def show
  end

  protected

  def project
    @project = Project.find(params[:project_id])
  end

  def set_runner
    @runner ||= @project.runners.find(params[:id])
  end

  def runner_params
    params.require(:runner).permit(:description, :tag_list, :contacted_at, :active)
  end
end

app/helpers/runners_helper.rb
module RunnersHelper
  def runner_status_icon(runner)
    unless runner.contacted_at
      return content_tag :i, nil,
        class: "icon-warning-sign",
        title: "New runner. Has not connected yet"
    end

    status =
      if runner.active?
        runner.contacted_at > 3.hour.ago ? :online : :offline
      else
        :paused
      end

    content_tag :i, nil,
      class: "icon-circle runner-status-#{status}",
      title: "Runner is #{status}, last contact was #{time_ago_in_words(runner.contacted_at)} ago"
  end
end

app/views/runners/_runner.html.haml
%li.runner{id: dom_id(runner)}
  %h4
    = runner_status_icon(runner)
    %span.monospace
      - if @runners.include?(runner)
        = link_to runner.short_sha, [@project, runner]
        %small
          =link_to edit_project_runner_path(@project, runner) do
            %i.fa.icon-edit.btn
      - else
        = runner.short_sha

    .pull-right
      - if @runners.include?(runner)
        - if runner.belongs_to_one_project?
          = link_to 'Remove runner', [@project, runner], data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-danger btn-sm'
        - else
          - runner_project = @project.runner_projects.find_by(runner_id: runner)
          = link_to 'Disable for this project', [@project, runner_project], data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-danger btn-sm'
      - elsif runner.specific?
        = form_for [@project, @project.runner_projects.new] do |f|
          = f.hidden_field :runner_id, value: runner.id
          = f.submit 'Enable for this project', class: 'btn btn-sm'
  .pull-right
    %small.light
      \##{runner.id}
  - if runner.description.present?
    %p.runner-description
      = runner.description
  - if runner.tag_list.present?
    %p
      - runner.tag_list.each do |tag|
        %span.label.label-primary
          = tag

app/views/runners/_shared_runners.html.haml
%h3 Shared runners

.bs-callout.bs-callout-warning
  GitLab Runners do not offer secure isolation between projects that they do builds for. You are TRUSTING all GitLab users who can push code to project A, B or C to run shell scripts on the machine hosting runner X.
  %hr
  - if @project.shared_runners_enabled
    = link_to toggle_shared_runners_project_path(@project), class: 'btn btn-warning', method: :post do
      Disable shared runners
  - else
    = link_to toggle_shared_runners_project_path(@project), class: 'btn btn-success', method: :post do
      Enable shared runners
  &nbsp; for this project

- if @shared_runners_count.zero?
  This application has no shared runners yet.
  Please use specific runners or ask administrator to create one
- else
  %h4.underlined-title Available shared runners - #{@shared_runners_count}
  %ul.bordered-list.available-shared-runners
    = render @shared_runners.first(10)
  - if @shared_runners_count > 10
    .light
      and #{@shared_runners_count - 10} more...

app/views/runners/_specific_runners.html.haml
%h3 Specific runners

.bs-callout.help-callout
  %h4 How to setup a new project specific runner

  %ol
    %li
      Install GitLab Runner software.
      Checkout the #{link_to 'GitLab Runner section', 'https://about.gitlab.com/gitlab-ci/#gitlab-runner', target: '_blank'} to install it
    %li
      Specify following URL during runner setup:
      %code #{root_url(only_path: false)}
    %li
      Use the following registration token during setup:
      %code #{@project.token}
    %li
      Start runner!


- if @runners.any?
  %h4.underlined-title Runners activated for this project
  %ul.bordered-list.activated-specific-runners
    = render @runners

- if @specific_runners.any?
  %h4.underlined-title Available specific runners
  %ul.bordered-list.available-specific-runners
    = render @specific_runners
  = paginate @specific_runners

app/views/runners/edit.html.haml
%h4 Runner ##{@runner.id}
%hr
= form_for [@project, @runner], html: { class: 'form-horizontal' } do |f|
  .form-group
    = label :active, "Active", class: 'control-label'
    .col-sm-10
      .checkbox
        = f.check_box :active
        %span.light Paused runners don't accept new builds
  .form-group
    = label_tag :token, class: 'control-label' do
      Token
    .col-sm-10
      = f.text_field :token, class: 'form-control', readonly: true
  .form-group
    = label_tag :description, class: 'control-label' do
      Description
    .col-sm-10
      = f.text_field :description, class: 'form-control'
  .form-group
    = label_tag :tag_list, class: 'control-label' do
      Tags
    .col-sm-10
      = f.text_field :tag_list, class: 'form-control'
      .help-block You can setup jobs to only use runners with specific tags
  .form-actions
    = f.submit 'Save', class: 'btn btn-save'

app/views/runners/index.html.haml
.light
  %p
    A 'runner' is a process which runs a build.
    You can setup as many runners as you need.
    %br
    Runners can be placed on separate users, servers, and even on your local machine.

  %p Each runner can be in one of the following states:
  %div
    %ul
      %li
        %span.label.label-success active
        \- runner is active and can process any new build
      %li
        %span.label.label-danger paused
        \- runner is paused and will not receive any new build

%hr

%p.lead To start serving your builds you can either add specific runners to your project or use shared runners
.row
  .col-sm-6
    = render 'specific_runners'
  .col-sm-6
    = render 'shared_runners'

app/views/runners/show.html.haml
= content_for :title do
  %h3.project-title
    Runner ##{@runner.id}
    .pull-right
      - if @runner.shared?
        %span.runner-state.runner-state-shared
          Shared
      - else
        %span.runner-state.runner-state-specific
          Specific

%table.table
  %thead
    %tr
      %th Property Name
      %th Value
  %tr
    %td
      Tags
    %td
      - @runner.tag_list.each do |tag|
        %span.label.label-primary
          = tag
  %tr
    %td
      Name
    %td
      = @runner.name
  %tr
    %td
      Version
    %td
      = @runner.version
  %tr
    %td
      Revision
    %td
      = @runner.revision
  %tr
    %td
      Platform
    %td
      = @runner.platform
  %tr
    %td
      Architecture
    %td
      = @runner.architecture
  %tr
    %td
      Description
    %td
      = @runner.description
  %tr
    %td
      Last contact
    %td
      - if @runner.contacted_at
        #{time_ago_in_words(@runner.contacted_at)} ago
      - else
        Never


      