config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resource :lint, only: [:show, :create]

  resource :help do
    get :oauth2
  end

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status, to: 'projects#badge'
      get :integration
      post :build
      post :toggle_shared_runners
      get :dumped_yaml
    end

    resources :services, only: [:index, :edit, :update] do
      member do
        get :test
      end
    end

    resource :charts, only: [:show]

    resources :refs, constraints: { ref_id: /.*/ }, only: [] do
      resources :commits, only: [:show] do
        member do
          get :status
          get :cancel
        end
      end
    end

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :web_hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end

    resources :triggers, only: [:index, :create, :destroy]

    resources :runners, only: [:index, :edit, :update, :destroy, :show] do
      member do
        get :resume
        get :pause
      end
    end

    resources :runner_projects, only: [:create, :destroy]

    resources :events, only: [:index]
    resource :variables, only: [:show, :update]
  end

  resource :user_sessions do
    get :auth
    get :callback
  end

  namespace :admin do
    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        put :assign_all
        get :resume
        get :pause
      end
    end

    resources :events, only: [:index]

    resources :projects do
      resources :runner_projects
    end

    resources :builds, only: :index

    resource :application_settings, only: [:show, :update]
  end

  root to: 'projects#index'
end

app/models/runner_project.rb
# == Schema Information
#
# Table name: runner_projects
#
#  id         :integer          not null, primary key
#  runner_id  :integer          not null
#  project_id :integer          not null
#  created_at :datetime
#  updated_at :datetime
#

class RunnerProject < ActiveRecord::Base
  belongs_to :runner
  belongs_to :project

  validates_uniqueness_of :runner_id, scope: :project_id
end

app/controllers/admin/runner_projects_controller.rb
class Admin::RunnerProjectsController < Admin::ApplicationController
  layout 'project'

  def index
    @runner_projects = project.runner_projects.all
    @runner_project = project.runner_projects.new
  end

  def create
    @runner = Runner.find(params[:runner_project][:runner_id])

    if @runner.assign_to(project, current_user)
      redirect_to admin_runner_path(@runner)
    else
      redirect_to admin_runner_path(@runner), alert: 'Failed adding runner to project'
    end
  end

  def destroy
    rp = RunnerProject.find(params[:id])
    runner = rp.runner
    rp.destroy

    redirect_to admin_runner_path(runner)
  end

  private

  def project
    @project ||= Project.find(params[:project_id])
  end
end

app/controllers/runner_projects_controller.rb
class RunnerProjectsController < ApplicationController
  before_filter :authenticate_user!
  before_filter :project
  before_filter :authorize_manage_project!

  layout 'project'

  def create
    @runner = Runner.find(params[:runner_project][:runner_id])

    return head(403) unless current_user.authorized_runners.include?(@runner)

    if @runner.assign_to(project, current_user)
      redirect_to project_runners_path(project)
    else
      redirect_to project_runners_path(project), alert: 'Failed adding runner to project'
    end
  end

  def destroy
    runner_project = project.runner_projects.find(params[:id])
    runner_project.destroy

    redirect_to project_runners_path(project)
  end

  private

  def project
    @project ||= Project.find(params[:project_id])
  end
end

app/views/admin/runner_projects/index.html.haml
%p.lead
  To register new runner visit #{link_to 'this page ', runners_path}

.row
  .col-md-8
    %h5 Activated:
    %table.table
      %tr
        %th Runner ID
        %th Runner Description
        %th Last build
        %th Builds Stats
        %th Registered
        %th

      - @runner_projects.each do |runner_project|
        - runner = runner_project.runner
        - builds = runner.builds.where(project_id: @project.id)
        %tr
          %td
            %span.badge.badge-info= runner.id
          %td
            = runner.display_name
          %td
            - last_build = builds.last
            - if last_build
              = link_to last_build.short_sha, [last_build.project, last_build]
            - else
              unknown
          %td
            %span.badge.badge-success
              #{builds.success.count}
            %span /
            %span.badge.badge-important
              #{builds.failed.count}
          %td
            #{time_ago_in_words(runner_project.created_at)} ago
          %td
            = link_to 'Disable', [@project, runner_project], data: { confirm: "Are you sure?" }, method: :delete, class: 'btn btn-danger btn-sm right'
  .col-md-4
    %h5 Available
    %table.table
      %tr
        %th ID
        %th Token
        %th

      - (Runner.all - @project.runners).each do |runner|
        %tr
          %td
            = runner.id
          %td
            = runner.token
          %td
            = form_for [@project, @runner_project] do |f|
              = f.hidden_field :runner_id, value: runner.id
              = f.submit 'Add', class: 'btn btn-sm'