config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  # API
  API::API.logger Rails.logger
  mount API::API => '/api'

  resource :lint, only: [:show, :create]

  resource :help do
    get :oauth2
  end

  resources :projects do
    collection do
      post :add
      get :gitlab
    end

    member do
      get :status, to: 'projects#badge'
      get :integration
      post :build
      post :toggle_shared_runners
      get :dumped_yaml
    end

    resources :services, only: [:index, :edit, :update] do
      member do
        get :test
      end
    end

    resource :charts, only: [:show]

    resources :refs, constraints: { ref_id: /.*/ }, only: [] do
      resources :commits, only: [:show] do
        member do
          get :status
          get :cancel
        end
      end
    end

    resources :builds, only: [:show] do
      member do
        get :cancel
        get :status
        post :retry
      end
    end

    resources :web_hooks, only: [:index, :create, :destroy] do
      member do
        get :test
      end
    end

    resources :triggers, only: [:index, :create, :destroy]

    resources :runners, only: [:index, :edit, :update, :destroy, :show] do
      member do
        get :resume
        get :pause
      end
    end

    resources :runner_projects, only: [:create, :destroy]

    resources :events, only: [:index]
    resource :variables, only: [:show, :update]
  end

  resource :user_sessions do
    get :auth
    get :callback
  end

  namespace :admin do
    resources :runners, only: [:index, :show, :update, :destroy] do
      member do
        put :assign_all
        get :resume
        get :pause
      end
    end

    resources :events, only: [:index]

    resources :projects do
      resources :runner_projects
    end

    resources :builds, only: :index

    resource :application_settings, only: [:show, :update]
  end

  root to: 'projects#index'
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id                       :integer          not null, primary key
#  name                     :string(255)      not null
#  timeout                  :integer          default(3600), not null
#  created_at               :datetime
#  updated_at               :datetime
#  token                    :string(255)
#  default_ref              :string(255)
#  path                     :string(255)
#  always_build             :boolean          default(FALSE), not null
#  polling_interval         :integer
#  public                   :boolean          default(FALSE), not null
#  ssh_url_to_repo          :string(255)
#  gitlab_id                :integer
#  allow_git_fetch          :boolean          default(TRUE), not null
#  email_recipients         :string(255)      default(""), not null
#  email_add_pusher         :boolean          default(TRUE), not null
#  email_only_broken_builds :boolean          default(TRUE), not null
#  skip_refs                :string(255)
#  coverage_regex           :string(255)
#  shared_runners_enabled   :boolean          default(FALSE)
#  generated_yaml_config    :text
#

class Project < ActiveRecord::Base
  include ProjectStatus

  has_many :commits, ->() { order('CASE WHEN commits.committed_at IS NULL THEN 0 ELSE 1 END', :committed_at, :id) }, dependent: :destroy
  has_many :builds, through: :commits, dependent: :destroy
  has_many :runner_projects, dependent: :destroy
  has_many :runners, through: :runner_projects
  has_many :web_hooks, dependent: :destroy
  has_many :events, dependent: :destroy
  has_many :variables, dependent: :destroy
  has_many :triggers, dependent: :destroy

  # Project services
  has_many :services, dependent: :destroy
  has_one :hip_chat_service, dependent: :destroy
  has_one :slack_service, dependent: :destroy
  has_one :mail_service, dependent: :destroy

  accepts_nested_attributes_for :variables, allow_destroy: true

  #
  # Validations
  #
  validates_presence_of :name, :timeout, :token, :default_ref,
    :path, :ssh_url_to_repo, :gitlab_id

  validates_uniqueness_of :gitlab_id

  validates :polling_interval,
    presence: true,
    if: ->(project) { project.always_build.present? }

  scope :public_only, ->() { where(public: true) }

  before_validation :set_default_values

  class << self
    include CurrentSettings

    def base_build_script
      <<-eos
git submodule update --init
ls -la
      eos
    end

    def parse(project)
      params = {
        name:                     project.name_with_namespace,
        gitlab_id:                project.id,
        path:                     project.path_with_namespace,
        default_ref:              project.default_branch || 'master',
        ssh_url_to_repo:          project.ssh_url_to_repo,
        email_add_pusher:         current_application_settings.add_pusher,
        email_only_broken_builds: current_application_settings.all_broken_builds,
      }

      project = Project.new(params)
      project.build_missing_services
      project
    end

    def from_gitlab(user, scope = :owned, options)
      opts = user.authenticate_options
      opts.merge! options

      projects = Network.new.projects(opts.compact, scope)

      if projects
        projects.map { |pr| OpenStruct.new(pr) }
      else
        []
      end
    end

    def already_added?(project)
      where(gitlab_id: project.id).any?
    end

    def unassigned(runner)
      joins('LEFT JOIN runner_projects ON runner_projects.project_id = projects.id ' \
        "AND runner_projects.runner_id = #{runner.id}").
      where('runner_projects.project_id' => nil)
    end

    def ordered_by_last_commit_date
      last_commit_subquery = "(SELECT project_id, MAX(committed_at) committed_at FROM commits GROUP BY project_id)"
      joins("LEFT JOIN #{last_commit_subquery} AS last_commit ON projects.id = last_commit.project_id").
        order("CASE WHEN last_commit.committed_at IS NULL THEN 1 ELSE 0 END, last_commit.committed_at DESC")
    end

    def search(query)
      where('LOWER(projects.name) LIKE :query',
            query: "%#{query.try(:downcase)}%")
    end
  end

  def any_runners?
    if runners.active.any?
      return true
    end

    shared_runners_enabled && Runner.shared.active.any?
  end

  def set_default_values
    self.token = SecureRandom.hex(15) if self.token.blank?
  end

  def tracked_refs
    @tracked_refs ||= default_ref.split(",").map{|ref| ref.strip}
  end

  def valid_token? token
    self.token && self.token == token
  end

  def no_running_builds?
    # Get running builds not later than 3 days ago to ignore hangs
    builds.running.where("updated_at > ?", 3.days.ago).empty?
  end

  def email_notification?
    email_add_pusher || email_recipients.present?
  end

  def web_hooks?
    web_hooks.any?
  end

  def services?
    services.any?
  end

  def timeout_in_minutes
    timeout / 60
  end

  def timeout_in_minutes=(value)
    self.timeout = value.to_i * 60
  end

  def coverage_enabled?
    coverage_regex.present?
  end

  # Build a clone-able repo url
  # using http and basic auth
  def repo_url_with_auth
    auth = "gitlab-ci-token:#{token}@"
    url = gitlab_url + ".git"
    url.sub(/^https?:\/\//) do |prefix|
      prefix + auth
    end
  end

  def available_services_names
    %w(slack mail hip_chat)
  end

  def build_missing_services
    available_services_names.each do |service_name|
      service = services.find { |service| service.to_param == service_name }

      # If service is available but missing in db
      # we should create an instance. Ex `create_gitlab_ci_service`
      service = self.send :"create_#{service_name}_service" if service.nil?
    end
  end

  def execute_services(data)
    services.each do |service|

      # Call service hook only if it is active
      begin
        service.execute(data) if service.active && service.can_execute?(data)
      rescue => e
        logger.error(e)
      end
    end
  end

  def gitlab_url
    File.join(GitlabCi.config.gitlab_server.url, path)
  end

  def setup_finished?
    commits.any?
  end
end

app/controllers/admin/projects_controller.rb
class Admin::ProjectsController < Admin::ApplicationController
  def index
    @projects = Project.ordered_by_last_commit_date.page(params[:page]).per(30)
  end

  def destroy
    project.destroy

    redirect_to projects_url
  end

  protected

  def project
    @project ||= Project.find(params[:id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  PROJECTS_BATCH = 100

  before_filter :authenticate_user!, except: [:build, :badge, :index, :show]
  before_filter :authenticate_public_page!, only: :show
  before_filter :project, only: [:build, :integration, :show, :badge, :edit, :update, :destroy, :toggle_shared_runners, :dumped_yaml]
  before_filter :authorize_access_project!, except: [:build, :gitlab, :badge, :index, :show, :new, :create]
  before_filter :authorize_manage_project!, only: [:edit, :integration, :update, :destroy, :toggle_shared_runners, :dumped_yaml]
  before_filter :authenticate_token!, only: [:build]
  before_filter :no_cache, only: [:badge]
  protect_from_forgery except: :build

  layout 'project', except: [:index, :gitlab]

  def index
    @projects = Project.ordered_by_last_commit_date.public_only.page(params[:page]) unless current_user
  end

  def gitlab
    @limit, @offset = (params[:limit] || PROJECTS_BATCH).to_i, (params[:offset] || 0).to_i
    @page = @offset == 0 ? 1 : (@offset / @limit + 1)

    current_user.reset_cache if params[:reset_cache]

    @gl_projects = current_user.gitlab_projects(params[:search], @page, @limit)
    @projects = Project.where(gitlab_id: @gl_projects.map(&:id)).ordered_by_last_commit_date
    @total_count = @gl_projects.size
    @gl_projects.reject! { |gl_project| @projects.map(&:gitlab_id).include?(gl_project.id) }
    respond_to do |format|
      format.json do
        pager_json("projects/gitlab", @total_count)
      end
    end
  rescue Network::UnauthorizedError
    raise
  rescue
    @error = 'Failed to fetch GitLab projects'
  end

  def show
    @ref = params[:ref]

    @commits = @project.commits.reverse_order
    @commits = @commits.where(ref: @ref) if @ref
    @commits = @commits.page(params[:page]).per(20)
  end

  def integration
  end

  def create
    project_data = OpenStruct.new(JSON.parse(params["project"]))

    unless current_user.can_manage_project?(project_data.id)
      return redirect_to root_path, alert: 'You have to have at least master role to enable CI for this project'
    end

    @project = CreateProjectService.new.execute(current_user, project_data, project_url(":project_id"))

    if @project.persisted?
      redirect_to project_path(@project, show_guide: true), notice: 'Project was successfully created.'
    else
      redirect_to :back, alert: 'Cannot save project'
    end
  end

  def edit
  end

  def update
    if project.update_attributes(project_params)
      EventService.new.change_project_settings(current_user, project)

      redirect_to :back, notice: 'Project was successfully updated.'
    else
      render action: "edit"
    end
  end

  def destroy
    project.destroy
    Network.new.disable_ci(project.gitlab_id, current_user.authenticate_options)

    EventService.new.remove_project(current_user, project)

    redirect_to projects_url
  end

  def build
    @commit = CreateCommitService.new.execute(@project, params.dup)

    if @commit && @commit.valid?
      head 201
    else
      head 400
    end
  end

  # Project status badge
  # Image with build status for sha or ref
  def badge
    image = ImageForBuildService.new.execute(@project, params)

    send_file image.path, filename: image.name, disposition: 'inline', type:"image/svg+xml"
  end

  def toggle_shared_runners
    project.toggle!(:shared_runners_enabled)
    redirect_to :back
  end

  def dumped_yaml
    send_data @project.generated_yaml_config, filename: '.gitlab-ci.yml'
  end

  protected

  def project
    @project ||= Project.find(params[:id])
  end

  def no_cache
    response.headers["Cache-Control"] = "no-cache, no-store, max-age=0, must-revalidate"
    response.headers["Pragma"] = "no-cache"
    response.headers["Expires"] = "Fri, 01 Jan 1990 00:00:00 GMT"
  end

  def project_params
    params.require(:project).permit(:path, :timeout, :timeout_in_minutes, :default_ref, :always_build,
      :polling_interval, :public, :ssh_url_to_repo, :allow_git_fetch, :email_recipients,
      :email_add_pusher, :email_only_broken_builds, :coverage_regex, :shared_runners_enabled, :token,
      { variables_attributes: [:id, :key, :value, :_destroy] })
  end
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def ref_tab_class ref = nil
    'active' if ref == @ref
  end

  def success_ratio(success_builds, failed_builds)
    failed_builds = failed_builds.count(:all)
    success_builds = success_builds.count(:all)

    return 100 if failed_builds.zero?

    ratio = (success_builds.to_f / (success_builds + failed_builds)) * 100
    ratio.to_i
  end

  def markdown_badge_code(project, ref)
    url = status_project_url(project, ref: ref, format: 'png')
    "[![build status](#{url})](#{project_url(project, ref: ref)})"
  end

  def html_badge_code(project, ref)
    url = status_project_url(project, ref: ref, format: 'png')
    "<a href='#{project_url(project, ref: ref)}'><img src='#{url}' /></a>"
  end

  def project_uses_specific_runner?(project)
    project.runners.any?
  end

  def no_runners_for_project?(project)
    project.runners.blank? &&
      Runner.shared.blank?
  end
end

app/views/projects/_form.html.haml
.bs-callout.help-callout
  %p
    If you want to test your .gitlab-ci.yml, you can use special tool - #{link_to "Lint", lint_path}
  %p
    Edit your 
    #{link_to ".gitlab-ci.yml using web-editor", yaml_web_editor_link(@project)}

= nested_form_for @project, html: { class: 'form-horizontal' } do |f|
  - if @project.errors.any?
    #error_explanation
      %p.lead= "#{pluralize(@project.errors.count, "error")} prohibited this project from being saved:"
      .alert.alert-error
        %ul
          - @project.errors.full_messages.each do |msg|
            %li= msg

  %fieldset
    %legend Build settings
    .form-group
      = label_tag nil, class: 'control-label' do
        Get code
      .col-sm-10
        %p Get recent application code using the following command:
        .radio
          = label_tag do
            = f.radio_button :allow_git_fetch, 'false'
            %strong git clone
            .light Slower but makes sure you have a clean dir before every build
        .radio
          = label_tag do
            = f.radio_button :allow_git_fetch, 'true'
            %strong git fetch
            .light Faster
    .form-group
      = f.label :timeout_in_minutes, 'Timeout', class: 'control-label'
      .col-sm-10
        = f.number_field :timeout_in_minutes, class: 'form-control', min: '0'
        .light per build in minutes


  %fieldset
    %legend Build Schedule
    .form-group
      = f.label :always_build, 'Schedule build', class: 'control-label'
      .col-sm-10
        .checkbox
          = f.label :always_build do
            = f.check_box :always_build
            %span.light Repeat last build after X hours if no builds
    .form-group
      = f.label :polling_interval, "Build interval", class: 'control-label'
      .col-sm-10
        = f.number_field :polling_interval, placeholder: '5', min: '0', class: 'form-control'
        .light In hours

  %fieldset
    %legend Project settings
    .form-group
      = f.label :default_ref, "Make tabs for the following branches", class: 'control-label'
      .col-sm-10
        = f.text_field :default_ref, class: 'form-control', placeholder: 'master, stable'
        .light You will be able to filter builds by the following branches
    .form-group
      = f.label :public, 'Public mode', class: 'control-label'
      .col-sm-10
        .checkbox
          = f.label :public do
            = f.check_box :public
            %span.light Anyone can see project and builds
    .form-group
      = f.label :coverage_regex, "Test coverage parsing", class: 'control-label'
      .col-sm-10
        .input-group
          %span.input-group-addon /
          = f.text_field :coverage_regex, class: 'form-control', placeholder: '\(\d+.\d+\%\) covered'
          %span.input-group-addon /
        .light We will use this regular expression to find test coverage output in build trace. Leave blank if you want to disable this feature
        .bs-callout.bs-callout-info
          %p Below are examples of regex for existing tools:
          %ul
            %li
              Simplecov (Ruby) -
              %code \(\d+.\d+\%\) covered
            %li
              pytest-cov (Python) -
              %code \d+\%$



  %fieldset
    %legend Advanced settings
    .form-group
      = f.label :token, "CI token", class: 'control-label'
      .col-sm-10
        = f.text_field :token, class: 'form-control', placeholder: 'xEeFCaDAB89'
    
  .form-actions
    = f.submit 'Save changes', class: 'btn btn-save'
    = link_to 'Cancel', projects_path, class: 'btn'
    - unless @project.new_record?
      = link_to 'Remove Project', project_path(@project), method: :delete, data: { confirm: 'Project will be removed. Are you sure?' }, class: 'btn btn-danger pull-right'

app/views/projects/_gl_projects.html.haml
- @gl_projects.sort_by(&:name_with_namespace).each do |project|
  %tr.light
    %td
      = project.name_with_namespace
    %td
      %small Not added to CI
    %td
    %td
      - if Project.already_added?(project)
        %strong.cgreen
          Added
      - else
        = form_tag projects_path do
          = hidden_field_tag :project, project.to_h.to_json
          = submit_tag 'Add project to CI', class: 'btn btn-default btn-sm'

app/views/projects/_info.html.haml
- if no_runners_for_project?(@project)
  = render 'no_runners'

app/views/projects/_no_runners.html.haml
.alert.alert-danger
  %p
    There are NO runners to build this project.
    %br
    You can add Specific runner for this project on Runners page

    - if current_user.is_admin
      or add Shared runner for whole application in admin are.

app/views/projects/_project.html.haml
- last_commit = project.last_commit
%tr.alert{class: commit_status_alert_class(last_commit) }
  %td
    = link_to project do
      %strong= project.name
  %td
    - if last_commit
      #{last_commit.status} (#{commit_link(last_commit)})
      - if project.last_commit_date
        = time_ago_in_words project.last_commit_date
        ago
    - else
      No builds yet
  %td
    - if project.public
      %i.icon-globe
      Public
    - else
      %i.icon-lock
      Private
  %td
    = project.commits.count

app/views/projects/_public.html.haml
= content_for :title do
  %h3.project-title
    Public projects

.bs-callout
  = link_to new_user_sessions_path(state: generate_oauth_state(request.fullpath)) do
    %strong Login with GitLab
  to see your private projects

- if @projects.present?
  .projects
    %table.table
      %tr
        %th Name
        %th Last commit
        %th Access
        %th Commits
      = render @projects
  = paginate @projects
- else
  %h4 No public projects yet

app/views/projects/_search.html.haml
.search
  = form_tag "#", method: :get, class: 'navbar-form' do |f|
    .form-group
      .input-group
        = search_field_tag "search", params[:search], placeholder: "Search", class: "search-input form-control"
        .input-group-addon
          %i.icon-search


:coffeescript
  $('.search .navbar-form').submit ->
    NProgress.start()
    query = $('.search .navbar-form .search-input').val()
    $.get '#{gitlab_projects_path}', { search: query }, (data) ->
      $(".projects").html data.html
      NProgress.done()
    Pager.init "#{gitlab_projects_path}" + "?search=" + query, #{ProjectsController::PROJECTS_BATCH}, false
    false

app/views/projects/edit.html.haml
- if @project.generated_yaml_config
  %p.alert.alert-danger
    CI Jobs are deprecated now, you can #{link_to "download", dumped_yaml_project_path(@project)} 
    or
    %a.preview-yml{:href => "#yaml-content", "data-toggle" => "modal"} preview
    yaml file which is based on your old jobs.
    Put this file to the root of your project and name it .gitlab-ci.yml

= render 'form'

- if @project.generated_yaml_config
  #yaml-content.modal.fade{"aria-hidden" => "true", "aria-labelledby" => ".gitlab-ci.yml", :role => "dialog", :tabindex => "-1"}
    .modal-dialog
      .modal-content
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
          %h4.modal-title Content of .gitlab-ci.yml
        .modal-body
          = text_area_tag :yaml, @project.generated_yaml_config, size: "70x25", class: "form-control"
        .modal-footer
          %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close

app/views/projects/gitlab.html.haml
- if @offset == 0
  .clearfix.light
    .pull-left.fetch-status
      Fetched from GitLab (#{link_to GitlabCi.config.gitlab_server.url, GitlabCi.config.gitlab_server.url, no_turbolink})
      - if params[:search].present?
        by keyword: "#{params[:search]}",
      #{time_ago_in_words(current_user.sync_at)} ago.
      = link_to gitlab_projects_path(reset_cache: true, search: params[:search]), class: 'sync-now btn btn-sm btn-default reset-cache' do
        %i.icon-refresh
        Sync now
      %br

    .pull-right
      #{@total_count} projects, #{@projects.size} of them added to CI
  %br

  %table.table.projects-table.content-list
    %thead
      %tr
        %th Project Name
        %th Last commit
        %th Access
        %th Commits

    = render @projects

    = render "gl_projects"

  %p.text-center.hide.loading
    %i.icon-refresh.icon-spin

- else
  = render @projects

  = render "gl_projects"

app/views/projects/index.html.haml
- if current_user
  = content_for :title do
    %h3.project-title
      Dashboard
      .pull-right
        = render "search"

  .projects
    %p.fetch-status.light
      %i.icon-refresh.icon-spin
      Please wait while we fetch from GitLab (#{GitlabCi.config.gitlab_server.url})
  :coffeescript
    $.get '#{gitlab_projects_path}', (data) ->
      $(".projects").html data.html
    $('.projects').on 'click', '.reset-cache', ->
      $.get '#{gitlab_projects_path}', { reset_cache: true }, (data) ->
        $(".projects").html data.html
      false
    Pager.init "#{gitlab_projects_path}", #{ProjectsController::PROJECTS_BATCH}, false
    
- else
  = render 'public'

app/views/projects/show.html.haml
= render 'shared/guide' unless @project.setup_finished?

- if current_user && current_user.can_manage_project?(@project.gitlab_id) && !@project.any_runners?
  .alert.alert-danger
    Builds for this project wont be served unless you configure runners on
    = link_to "Runners page", project_runners_path(@project)

%ul.nav.nav-tabs.append-bottom-20
  %li{class: ref_tab_class}
    = link_to 'All commits', project_path(@project)
  - @project.tracked_refs.each do |ref|
    %li{class: ref_tab_class(ref)}
      = link_to ref, project_path(@project, ref: ref)

  - if @ref && !@project.tracked_refs.include?(@ref)
    %li{class: 'active'}
      = link_to @ref, project_path(@project, ref: @ref)



- if @ref
  %p
    Paste build status image for #{@ref} with next link
    = link_to '#', class: 'badge-codes-toggle btn btn-default btn-xs' do
      Status Badge
    .badge-codes-block.bs-callout.bs-callout-info.hide
      %p
        Status badge for
        %span.label.label-info #{@ref}
        branch
      %div
        %label Markdown:
        = text_field_tag 'badge_md', markdown_badge_code(@project, @ref), readonly: true, class: 'form-control'
        %label Html:
        = text_field_tag 'badge_html', html_badge_code(@project, @ref), readonly: true, class: 'form-control'




%table.builds
  %thead
    %tr
      %th Status
      %th Commit
      %th Message
      %th Branch
      %th Total duration
      %th Finished at
      - if @project.coverage_enabled?
        %th Coverage

  = render @commits

= paginate @commits

- if @commits.empty?
  .bs-callout
    %h4 No commits yet